import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import { Category } from './components/basic demo/Category';
import { Garage } from './components/basic demo/Garage';
const root = ReactDOM.createRoot(document.getElementById('root'));
// root.render(<Index/>);
root.render(<Garage/>);